### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by zachariahtimothy** [stipsan/react-uikit#1]
Hello there, I was going to create a React JS library for UIKit similar to the bootstrap one: https://github.com/react-bootstrap/react-bootstrap/. I prefer UIKit to Bootstrap but I do not want to reinvent the wheel. Can I give you a hand at all creating this library, or are you planning to commit any more? If not I will create a new one. Thanks!

**Comment by stipsan** [comment]
Hey, yes I do plan on working on it.I want to draw inspiration from http://material-ui.com/ in addition to react-bootstrap.
You're more than welcome to join in on the effort, no point in duplicating our efforts. I'll add you to the project right away :)

**Comment by zachariahtimothy** [comment]
Thanks so much! I thought it silly to create what you obviously were
working on.  I read the material UI spec last week, great stuff in there.
Just to clarify, you are planning on utilizing the UIKit (getuikit.com)
framework right?

_____________________________________
Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis <https://twitter.com/#!/@zachariahCurtis>
B: http://zachariahtimothy.wordpress.com/

**Comment by stipsan** [comment]
Yes, I am going to utilize UIkit by YOOtheme :)
