### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by zachariahtimothy** [stipsan/react-uikit#2]
Heya,
How do I do an npm install with react set to .13.0-rc2?  I get the following errors on both the code and docs:

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@0.12.4 wants react@0.12.x

Thanks!

**Comment by stipsan** [comment]
Heya :3, you have to update the peerDependencies locally.
The docs site is supposed to use react-router, like material-ui, but I'm still waiting for them to land React 0.13 support, you can follow progress here: https://github.com/rackt/react-router/issues/638

Jest is also broken if you update to the latest node version.

I'm going to refactor the docs page to not use react-router while we wait for them to fix the compat issues.
